### ISSUE TITLE
Crash caused by viewing a frame with an object whose outside property was changed

### ISSUE THREAD

**Issue by RDeticio** [Intelligent-Systems-Laboratory/sasha#12]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

The outside property of an annotation is used to indicate the end of an annotation track. As of the moment, this leads to a crash in the tool that should be fixed.

![image](https://user-images.githubusercontent.com/49665865/81370821-addeca80-9128-11ea-956a-4b234c657f46.png)

### Expected Behaviour

The annotator draws a box over an object in the current frame. Once the object leaves the frame, it's "outside property" is switched using a button in the menu that indicates that the object has left to frame. When the annotator wants to review this entire track of the object up to the point the object leaves the frame, they should be able to do so.

### Current Behaviour

The CVAT tool crashes, being caused by the change to the outside property of an annotation. It triggers when the frame in which the change was set is reviewed. The following error message appears:

TypeError
Cannot read property 'pinned' of undefined

TypeError: Cannot read property 'pinned' of undefined
    at cu.deactivateShape (http://103.231.240.106:8080/cvat-ui.min.js:72:1369585)
    at cu.deactivate (http://103.231.240.106:8080/cvat-ui.min.js:72:1369959)
    at cu.activate (http://103.231.240.106:8080/cvat-ui.min.js:72:1373006)
    at cu.notify (http://103.231.240.106:8080/cvat-ui.min.js:72:1358995)
    at Oc.notify (http://103.231.240.106:8080/cvat-ui.min.js:72:1291612)
    at Oc.activate (http://103.231.240.106:8080/cvat-ui.min.js:72:1295328)
    at pu.activate (http://103.231.240.106:8080/cvat-ui.min.js:72:1377077)
    at Yu.componentDidUpdate (http://103.231.240.106:8080/cvat-ui.min.js:72:1412421)
    at yl (http://103.231.240.106:8080/cvat-ui.min.js:43:100837)
    at t.unstable_runWithPriority (http://103.231.240.106:8080/cvat-ui.min.js:51:3465)

### Possible Solution

The console error logs refer to the file "canvasView.ts" located at "cvat/cvat-canvas/src/typescript". The TypeError points to the "pinned" property of the variable "drawnStates".

### Steps to Reproduce (for bugs)

1. Create an box annotation around an object
2. Switch outside property of box
3. Move to a different frame number
4. Move back to the frame number in which the annotation's outside property was changed
5. Wait until client crashes

### Context

The "switch outside property" indicates the frame number in which the object being tracked in an annotation leaves the frame.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by meyg8600** [comment]
**Commit hash:**
e97d60655f7d0965148429145656dc91a6e2a4d4

**Files edited:**

- cvat-canvas/src/typescript/canvasView.ts

**What we did to resolve this issue:**
We undid a few lines which deal with activating a shape in the canvasView code, which came from opencv/cvat. A similar fix was done before on commit 443e52d515fd42daeffdd10ff52e26e41b0ee742 on the jeff branch.
