### ISSUE TITLE
Frame is changing first before the bounding box follows in the tracking feature 

### ISSUE THREAD

**Issue by elcie3** [Intelligent-Systems-Laboratory/sasha#4]
### My actions before raising this issue
- [/] Searched [past issues](/issues)

### Expected Behaviour
The bounding box must move to the mouse position in the current frame so that the resulting bounding box will be in the place where the user placed the mouse. 

###Current Behaviour
When tracking mode is enable using the hotkey or the button in the UI and the player is playing, the frame will change first before moving the mouse. 

Files involved:
cvat/cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx

### Steps to Reproduce 
1. Enter the annotation screen of any task using the new UI.
2. Enable tracking mode by pressing 't' or using the button in the UI.
3. Use spacebar or the play button in the UI. 

### Context
The tracking feature should be able to move the bounding box to the mouse position on the frame that is currently annotated. With the current issue, the movement of the box is delayed for one frame. The effect is not noticeable when using the tracking mode when the player is playing. But, it greatly affects the user when annotating using the skip frame or next frame function. 

### Your Environment
- Git hash commit (`git log -1`): 6847ffc
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes? No
- Operating System and version (e.g. Linux, Windows, MacOS): Ubuntu

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by johnanthonyjose** [comment]
I can't seem to find some documentation for canvas.moved event?
[        canvasInstance.html().addEventListener('canvas.moved', this.getCursorLocation);](https://github.com/Intelligent-Systems-Laboratory/cvat/blob/aeb5012f2cd6a92819f43f378075b0b9e7cb1747/cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx#L856)

**Comment by johnanthonyjose** [comment]
Is this okay that we have two listeners on the event canvas.moved?

[        canvasInstance.html().addEventListener('canvas.moved', this.onCanvasCursorMoved);](https://github.com/Intelligent-Systems-Laboratory/cvat/blob/aeb5012f2cd6a92819f43f378075b0b9e7cb1747/cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx#L841)

**Comment by meyg8600** [comment]
**Commit hash:** 08ecbc1bafa02433cee26847ae8522fcff97cf77

**Files edited:**

- cvat-canvas/src/typescript/canvas.ts
- cvat-canvas/src/typescript/canvasController.ts
- cvat-canvas/src/typescript/canvasModel.ts
- cvat-canvas/src/typescript/canvasView.ts
- cvat-ui/src/actions/annotation-actions.ts
- cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
- cvat-ui/src/components/annotation-page/top-bar/player-buttons.tsx
- cvat-ui/src/components/annotation-page/top-bar/top-bar.tsx
- cvat-ui/src/containers/annotation-page/standard-workspace/canvas-wrapper.tsx
- cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
- cvat-ui/src/reducers/annotation-reducer.ts
- cvat-ui/src/reducers/interfaces.ts
- cvat-ui/src/reducers/shortcuts-reducer.ts

**What we did to solve the issue:**
Jeff transferred the implementation of the tracker from canvas-wrapper.tsx to canvasView.ts. A new rectangle was made to follow the mouse, and the original bounding box will go to the position of this new rectangle once clicked. The tracking feature can still be triggered by either pressing 't' or the play button on the right hand side of the top bar. A sub-feature which allows the user to change to size of the box was also added.
