### ISSUE TITLE
Switching the active box while playing: Clicking/Dragging a box while the player is playing will cause CVAT to crash

### ISSUE THREAD

**Issue by elcie3** [Intelligent-Systems-Laboratory/sasha#5]
### My actions before raising this issue
- [ /] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [ /] Searched [past issues](/issues)

### Expected Behaviour

The user should be able to change the box smoothly. 
### Current Behaviour

Changing the active box while playing causes CVAT to crash. 
Error
Canvas is busy. Action: drag

Error: Canvas is busy. Action: drag
    at au.activate (http://localhost:8080/cvat-ui.min.js:72:1336345)
    at Vu.activate (http://localhost:8080/cvat-ui.min.js:72:1403114)
    at Kc.activateOnCanvas (http://localhost:8080/cvat-ui.min.js:72:1321857)
    at Kc.componentDidUpdate (http://localhost:8080/cvat-ui.min.js:72:1318546)
    at yl (http://localhost:8080/cvat-ui.min.js:43:100837)
    at t.unstable_runWithPriority (http://localhost:8080/cvat-ui.min.js:51:3465)
    at Br (http://localhost:8080/cvat-ui.min.js:43:45441)
    at gl (http://localhost:8080/cvat-ui.min.js:43:97113)
    at ol (http://localhost:8080/cvat-ui.min.js:43:87489)
    at http://localhost:8080/cvat-ui.min.js:43:45732

### Steps to Reproduce (for bugs)

2 ways to reproduce the bug.
1st way. 
1. Create a new box but don't select it. 
2. Press the play button or the play hotkey.
3. Select the box you made.
2nd way.
1. Create two boxes. 
2. Press play
3. Select any of the boxes or switch from 1 box to another. 

### Context

When the user is using the 'tracking' feature that is added to CVAT, he/she might want to switch the box that is being tracked. With the current behavior this will result to a crash. This causes all the changes done in the session to be lost. This also results to bad user experience. 
### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by jeffersonkeh** [comment]
Additional method of reproducing bug:

1. Create a box.
2. Click and drag the box. Do not release the mouse button.
3. Change frame by pressing play, next frame, etc.

**Comment by meyg8600** [comment]
**Commit hashes:**
278e39e
9c0d2c1
1ef9631

**Files edited:**

- cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
- cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
- cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
- cvat-canvas/src/typescript/canvasModel.ts
- cvat-canvas/src/typescript/canvasView.ts
- cvat-core/src/annotations-collection.js
- cvat/apps/engine/static/engine/js/shapeMerger.js
- cvat-ui/src/cvat-canvas.ts
- cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
- cvat-ui/src/components/annotation-page/annotation-page.tsx
- cvat-ui/src/components/create-task-page/styles.scss
- cvat-ui/src/components/tasks-page/styles.scss
- cvat-ui/src/styles.scss

**What we did to resolve this issue:**
This was solved with the same fixes as Issue #8. We based this on the steps taken from PR opencv#1371 from opencv/cvat to resolve similar issues opencv#1261 and opencv#1371 in opencv/cvat.
