### ISSUE TITLE
Crosshair in zoom magnifying glass is inaccurate

### ISSUE THREAD

**Issue by jeffersonkeh** [Intelligent-Systems-Laboratory/sasha#6]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

The magnifying glass that appears when a user resizes a box should show the finer details around the resizing point. The crosshair in the magnifying glass should represent the resizing point of the box. However, there is sometimes a deviation between the point represented by the crosshair and the actual position of the resizing point.

### Expected Behaviour

The point in the middle of the crosshair should represent the resizing point of the bounding box.

### Current Behaviour

The point in the middle of the crosshair represents the position of the cursor.

### Possible Solution

Modify the function that shows the magnifying glass, specifically the part that makes use of the mouse coordinates.
cvat/cvat-canvas/src/typescript/canvasView.ts

### Steps to Reproduce (for bugs)

1. Create a bounding box
2. Choose a resize point and start resizing. Make use of the magnifying glass to try to accurately place the point on a specific location. Take note of the said location.
3. Increase the zoom of the background and check if the actual resize shows what was intended.
NOTE: This bug is more noticeable by clicking on the resizing point from the border of the circle.

### Context

The magnifying glass is intended to be used to accurately resize a box without needing to zoom into the background. It being not accurate defeats this purpose.

Intended location is on the corner of the white strip from the pedestrian lane.
![Screenshot from 2020-04-21 20-33-20](https://user-images.githubusercontent.com/49665836/79866708-c6a06e00-840f-11ea-8001-b942420b3b04.png)

Actual location is a small gap away from the intended location.
![Screenshot from 2020-04-21 20-35-30](https://user-images.githubusercontent.com/49665836/79866803-e6d02d00-840f-11ea-850b-c276945da4ab.png)

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by meyg8600** [comment]
**Commit hash:**
0ed6706bb1b3e4d5bbbc2e14aae27614061d5d61

**Files edited:**
- cvat-canvas/src/typescript/canvasView.ts

**What we did to resolve this issue:**
The method used to move the magnifying glass and draw the zoom magnifying glass were changed.
