### ISSUE TITLE
Autosnap feature gets unintentionally applied to a box.

### ISSUE THREAD

**Issue by jeffersonkeh** [Intelligent-Systems-Laboratory/sasha#7]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

The autosnap feature should be applied to a box only in the following circumstances.
1. When the box is created.
2. When the user intends to use the feature by double-clicking the box, pressing s, or through the context menu.
This bug allows the autosnap feature to be applied when changing to a frame that has more boxes than the previous frame.
Another effect of this bug is that upon changing frames, if the number of boxes in the new frame is greater than the number of boxes in the previous frame, the most recently created box gets 'activated'.

### Expected Behaviour

Changing frames should not call the autosnap feature.

### Current Behaviour

Upon changing frames, if the new frame contains more boxes than the previous frame, the auto snap feature is applied to the most recently made box.

### Possible Solution

cvat/cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
"if (annotations.length > prevProps.annotations.length)" does not check if a box is created (intended use case), rather, it checks if the current state of cvat-ui has more annotations than the previous state. Changing frames to a frame that has boxes not present in the previous frame passes this if statement.

### Steps to Reproduce (for bugs)

1. ensure project has no annotations (to avoid other factors)
2. Create a box and wait for it to get autosnapped.
3. Resize the box to overwrite autosnap.
4. Go to a frame that does not contain the previously created box.
5. Go to a frame that contains the previously created box. The frame that contains the box now has more boxes than the previous frame that does not contain the box, therefore the autosnap feature gets applied to the box.

### Context

The autosnap feature gets implemented outside its use case. This unintended action can remove the annotator's past work. If unnoticed, this causes incorrect annotations.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by meyg8600** [comment]
**Commit hash:** 3793aef0117550a6a2141035648d4640bd49a772

**Files edited:**
- cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx

**What I did to resolve this issue:**
I implemented the autoSnap function inside the contextMenuOnDraw function, instead of under "if (annotations.length > prevProps.annotations.length)" . This snaps the box directly after it is drawn, and does not trigger it upon changing frames.
