### ISSUE TITLE
Dragging/resizing a box during an autosnap process will cause CVAT to crash

### ISSUE THREAD

**Issue by RDeticio** [Intelligent-Systems-Laboratory/sasha#8]
### My actions before raising this issue
- [x] Read/searched [the docs](https://github.com/opencv/cvat/tree/master#documentation)
- [x] Searched [past issues](/issues)

CVAT currently is crashing indicating that the canvas is busy when either an annotation box is dragged or resized before the implemented auto-snap function occur.

### Expected Behaviour

The tool shouldn't crash and terminate itself. A user's actions on an annotation box should be independent of the auto-snap function and wouldn't conflict with each other. 

### Current Behaviour

The CVAT interface crashes returning one of two errors:

![image](https://user-images.githubusercontent.com/49665865/79872262-27cc3f80-8418-11ea-8b74-40e8872aa608.png)

1. If caused by dragging:

Error
Canvas is busy. Action: drag

Error: Canvas is busy. Action: drag
    at au.activate (http://localhost:8080/cvat-ui.min.js:72:1336345)
    at Vu.activate (http://localhost:8080/cvat-ui.min.js:72:1403114)
    at Kc.activateOnCanvas (http://localhost:8080/cvat-ui.min.js:72:1321857)
    at Kc.componentDidUpdate (http://localhost:8080/cvat-ui.min.js:72:1318546)
    at yl (http://localhost:8080/cvat-ui.min.js:43:100837)
    at t.unstable_runWithPriority (http://localhost:8080/cvat-ui.min.js:51:3465)
    at Br (http://localhost:8080/cvat-ui.min.js:43:45441)
    at gl (http://localhost:8080/cvat-ui.min.js:43:97113)
    at ol (http://localhost:8080/cvat-ui.min.js:43:87489)
    at http://localhost:8080/cvat-ui.min.js:43:45732

2. If caused by resizing:

Error
Canvas is busy. Action: resize

Error: Canvas is busy. Action: resize
    at au.activate (http://localhost:8080/cvat-ui.min.js:72:1336345)
    at Vu.activate (http://localhost:8080/cvat-ui.min.js:72:1403114)
    at Kc.activateOnCanvas (http://localhost:8080/cvat-ui.min.js:72:1321857)
    at Kc.componentDidUpdate (http://localhost:8080/cvat-ui.min.js:72:1318546)
    at yl (http://localhost:8080/cvat-ui.min.js:43:100837)
    at t.unstable_runWithPriority (http://localhost:8080/cvat-ui.min.js:51:3465)
    at Br (http://localhost:8080/cvat-ui.min.js:43:45441)
    at gl (http://localhost:8080/cvat-ui.min.js:43:97113)
    at ol (http://localhost:8080/cvat-ui.min.js:43:87489)
    at http://localhost:8080/cvat-ui.min.js:43:45732

### Possible Solution

It could be made so that it auto-snaps after the action on the box is finished, or it cancels the auto-snap when an action is taken on the box.

### Steps to Reproduce (for bugs)

1. Create a new box
![image](https://user-images.githubusercontent.com/49665865/79873229-6e6e6980-8419-11ea-9235-06036e2534a7.png)

2. Before the auto-snap function occurs, either click and hold the box itself or one of the resize points along it's edges.
![image](https://user-images.githubusercontent.com/49665865/79873418-abd2f700-8419-11ea-86dc-2d99f038a73d.png)
![image](https://user-images.githubusercontent.com/49665865/79873363-96f66380-8419-11ea-888b-ebf813a11497.png)

3. Wait for it to crash.

### Context

While the auto-snap function is part of the overall attempt to semi-automate the annotation process, the user might choose to manually control some of their boxes rather than waiting for the automatic snap to occur.

### Your Environment

- Git hash commit (`git log -1`):
- Docker version `docker version` (e.g. Docker 17.0.05):
- Are you using Docker Swarm or Kubernetes?
- Operating System and version (e.g. Linux, Windows, MacOS):
- Code example or link to GitHub repo or gist to reproduce problem:
- Other diagnostic information / logs:
    <details>
    <summary>Logs from `cvat` container</summary>
    </details>

### Next steps
You may [join our Gitter](https://gitter.im/opencv-cvat/public) channel for community support.

**Comment by meyg8600** [comment]
**Commit hashes:**
278e39ed965b1895bcf31448d3d41fd834728dbf
9c0d2c1ec1ac187b7dbfacc322636b6265ce1108
1ef96316def82044a07260bea0d7005f4016fb14


**Files edited:**

- cvat-ui/src/components/annotation-page/standard-workspace/canvas-wrapper.tsx
- cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/object-item.tsx
- cvat-ui/src/containers/annotation-page/standard-workspace/objects-side-bar/objects-list.tsx
- cvat-canvas/src/typescript/canvasModel.ts
- cvat-canvas/src/typescript/canvasView.ts
- cvat-core/src/annotations-collection.js
- cvat/apps/engine/static/engine/js/shapeMerger.js
- cvat-ui/src/cvat-canvas.ts
- cvat-ui/src/containers/annotation-page/top-bar/top-bar.tsx
- cvat-ui/src/components/annotation-page/annotation-page.tsx
- cvat-ui/src/components/create-task-page/styles.scss
- cvat-ui/src/components/tasks-page/styles.scss
- cvat-ui/src/styles.scss


**What we did to resolve this issue:**
We based this on the steps taken from PR #1371 from opencv/cvat to resolve similar issues #1261 and #1371 in opencv/cvat.
